### ISSUE TITLE
[Epic] Korok Seed Guide Feature

### ISSUE THREAD

**Issue by JohnKirubaharan** [JohnKirubaharan/Zelda_BOTW_L00187651#1]
This feature aims to help/guide players to locate all 900 Korok seeds in Zelda BOTW, by providing assistance based on credits spent by the players.

#### TASKS ###
- [ ] User Interface (UI) Design
- [ ] API Development for Seed Data Retrieval
- [ ] Integration of Credit System
- [ ] Level-based Hint System
- [ ] Testing and QA
- [ ] Documentation and Guides
